config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'

  get '/home/about' => 'homes#about', as: "about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    post 'follow' => 'relationships#follow', as: "follow"
    post 'unfollow' => 'relationships#unfollow', as: "unfollow"
    get 'followings' => 'relationships#followings', as: "followings"
    get 'followers' => 'relationships#followers', as: "followers"
  end
  
  get 'search' => "searches#search"



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #Userが新規作成されたあとにメールを送信するためのメソッド
  after_create :send_welcome_mail

  def send_welcome_mail
    NotificationMailer.complete_mail(self).deliver
  end

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followers, through: :followed, source: :follower
  has_many :followings, through: :follower, source: :followed

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE ?", "%#{words}")
    end
  end

  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
     if @user == current_user
       render :edit
     else
       redirect_to user_path(current_user)
     end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  
  

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<div class="profile-container">
  <h1>User info</h1>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th class="profile-name"><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th class="profile-introduction"><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th class="profile-followscount"><%= link_to user.follower.count, user_followings_path(user.id) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th class="profile-followerscount"><%= link_to user.followed.count, user_followers_path(user.id) %></th>
      </tr>
    </tbody>
  </table>
    
    <% if user.id == current_user.id %>
      <div class="row">
        <%= link_to "", edit_user_path(user), class: 'btn btn-outline-secondary btn-block btn-lg fas fa-user-cog' %>
      </div>
    <% end %>
    
    <% if user.id != current_user.id %>
      <% if current_user.following?(user) %>
        <div class="row">
          <%= link_to "フォロー外す", user_unfollow_path(user.id), method: :POST, class: 'btn btn-info' %>
        </div>
      <% else %>
        <div class="row">
          <%= link_to "フォローする", user_follow_path(user.id), method: :POST, class: 'btn btn-success' %>
        </div>
      <% end %>
    <% end %>

</div>

app/views/users/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

      <% if @user.errors.any? %>
        <%= @user.errors.count %>error
        <% @user.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>

      <h2>User info</h2>
      <%= form_with model:@user, local:true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: 'form-control name' %>
        </div>
        <div class="form-group">
          <label for="user_image">ProfileImage</label>
          <!--<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>-->
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: 'form-control-file user_image' %>
        </div>
        <div class="form-group">
          <label for="user_Introduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"自己紹介文", class: 'form-control introduction' %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: 'btn btn-secondary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/profile', user: @user %>
        <%= render 'books/new', booknew: @book %>
      </div>

  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
    <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
            <td><%= user.name %></td>
            <td><%= "フォロー数: #{user.follower.count}" %></td>
            <td><%= "フォロワー数: #{user.followed.count}" %></td>
            <td>
              <% if user.id != current_user.id %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_unfollow_path(user.id), method: :POST %>
                <% else %>
                  <%= link_to "フォローする", user_follow_path(user.id), method: :POST %>
                <% end %>
              <% end %>
            </td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/users/search.html.erb
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= "フォロー数: #{user.follower.count}" %></td>
          <td><%= "フォロワー数: #{user.followed.count}" %></td>
          <td>
            <% if user.id != current_user.id %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_unfollow_path(user.id), method: :POST %>
              <% else %>
                <%= link_to "フォローする", user_follow_path(user.id), method: :POST %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'users/profile', user: @user %>
            <%= render 'books/new', booknew: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <%= render 'books/list', books: @books %>
        </div>
    </div>
</div