config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'

  get '/home/about' => 'homes#about', as: "about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    post 'follow' => 'relationships#follow', as: "follow"
    post 'unfollow' => 'relationships#unfollow', as: "unfollow"
    get 'followings' => 'relationships#followings', as: "followings"
    get 'followers' => 'relationships#followers', as: "followers"
  end
  
  get 'search' => "searches#search"



end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @book = Book.where("title LIKE ?", "%#{words}%")
    elsif searches == "forward_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title LIKE ?", "%#{words}")
    end
  end


  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @booknew = Book.new
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        @user = current_user
        render :index
      end
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated"
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "Book was successfully destroyed"
      redirect_to books_path
    else
      render :new
    end
  end
  
  

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
    <h1>Books</h1>
    <table class="table table-hover table-inverse">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% books.each do |book| %>
          <tr>
            <%= link_to user_path(book.user.id) do %>
            <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
            <% end %>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td>
              <div id="favorites_buttons_<%= book.id %>">
                <%= render partial: 'favorites/favorite', locals: { book: book} %>
              </div>
            </td>
            <td>
              <p><%= link_to "コメント数: #{book.book_comments.count}", book_path(book.id) %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>  

app/views/books/_new.html.erb
<h2 class="mt-3">New book</h2>
  <% if booknew.errors.any? %>
    <% if booknew.errors.count == 1 %>
      <%= booknew.errors.count %>error
    <% else %>
      <%= booknew.errors.count %>errors
    <% end %>
    <% booknew.errors.full_messages.each do |message| %>
      <%= message %>
    <% end %>
  <% end %>

  <%= form_with model:booknew, local:true do |f| %>


  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Opinion</h4>
  <%= f.text_area :body %>

  <%= f.submit 'Create Book', class: 'btn btn-success' %>

<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= form_with model:@book, local:true do |f| %>
        <% if @book.errors.any? %>
          <% if @book.errors.count == 1 %>
            <%= @book.errors.count %>error
          <% else %>
            <%= @book.errors.count %>errors
          <% end %>
          <% @book.errors.full_messages.each do |message| %>
            <%= message %>
          <% end %>
        <% end %>
        <div class="form-group">
          <h4>Title</h4>
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <h4>Opinion</h4>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: 'btn btn-success' %>
        </div>
      <% end %>

      <%= link_to "Show", book_path(@book.id) %>
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <%= render 'users/profile', user: @user %>
        <%= render 'books/new', booknew: @book %>
      </div>

      <div class="col-md-8 offset-md-1">
        <%= render 'books/list', books: @books, users: @users %>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <%= render 'users/profile', user: @user %>
            <%= render 'books/new', booknew: @booknew %>
        </div>
    <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
            <tbody>
                <tr>
                    <td>
                        <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', fallback: "no_image.jpg" %>
                        <p><%= link_to @user.name, user_path(@user.id) %></p>
                    </td>
                    <td>
                        <%= @book.title %>
                    </td>
                    <td>
                        <%= @book.body %>
                    </td>
                    <td>
                        <% if @user.id == current_user.id %>
                            <td>
                                <%= link_to "Edit", edit_book_path(@book.id), class: 'btn btn-sm btn-success' %>
                            </td>
                            <td>
                            <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "Are you sure?", class: 'btn btn-sm btn-danger' %>
                            </td>
                        <% end %>

                        <% if @book.favorited_by?(current_user) %>
                            <td>
                                <%= link_to book_favorites_path(@book), method: :delete do %>
                                    ♥<%= @book.favorites.count %>
                                <% end %>
                            </td>
                        <% else %>
                            <td>
                                <%= link_to book_favorites_path(@book), method: :post do %>
                                    ♡<%= @book.favorites.count %>
                                <% end %>
                            </td>
                        <% end %>
                        <td colspan="3">
                           <p>コメント数:<%= @book.book_comments.count %></P>
                        </td>
                    </td>
                </tr>
            </tbody>
        </table>
        
        <div id="book_comment_area">
            <%= render partial: 'book_comments/index', locals: { book: @book } %>
        </div>
        
        <div class="new-comment">
            <%= render partial: 'book_comments/form', locals: { book: @book, book_comment: @book_comment } %>
        </div>

    </div>
</div>