config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'

  get '/home/about' => 'homes#about', as: "about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    post 'follow' => 'relationships#follow', as: "follow"
    post 'unfollow' => 'relationships#unfollow', as: "unfollow"
    get 'followings' => 'relationships#followings', as: "followings"
    get 'followers' => 'relationships#followers', as: "followers"
  end
  
  get 'search' => "searches#search"



end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
 
  def search
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searches/search.html.erb
<% if @range == "User" %>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <td><%= user.name %></td>
          <td><%= "フォロー数: #{user.follower.count}" %></td>
          <td><%= "フォロワー数: #{user.followed.count}" %></td>
          <td>
            <% if user.id != current_user.id %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_unfollow_path(user.id), method: :POST %>
              <% else %>
                <%= link_to "フォローする", user_follow_path(user.id), method: :POST %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to "Show", user_path(user.id) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>title</th>
        <th>opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <%= link_to user_path(book.user.id) do %>
            <td><%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
          <% end %>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>