config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'

  get '/home/about' => 'homes#about', as: "about"

  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:show, :edit, :update, :index] do
    post 'follow' => 'relationships#follow', as: "follow"
    post 'unfollow' => 'relationships#unfollow', as: "unfollow"
    get 'followings' => 'relationships#followings', as: "followings"
    get 'followers' => 'relationships#followers', as: "followers"
  end
  
  get 'search' => "searches#search"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @book = Book.where("title LIKE ?", "%#{words}%")
    elsif searches == "forward_match"
      @book = Book.where("title LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title LIKE ?", "%#{words}")
    end
  end


  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: { maximum: 200 }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #Userが新規作成されたあとにメールを送信するためのメソッド
  after_create :send_welcome_mail

  def send_welcome_mail
    NotificationMailer.complete_mail(self).deliver
  end

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followers, through: :followed, source: :follower
  has_many :followings, through: :follower, source: :followed

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.looks(searches, words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE ?", "%#{words}")
    end
  end

  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
    
  protected
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
  
  def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [
       :email,
       :name,
       :postcode,
       :prefecture_name,
       :address_city,
       :address_street,
       :address_building
      ])
     devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
    @users = User.all
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @booknew = Book.new
    @book_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
      if @book.save
        flash[:notice] = "Book was successfully created."
        redirect_to book_path(@book.id)
      else
        @books = Book.all
        @user = current_user
        render :index
      end
  end


  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated"
      redirect_to book_path(@book.id)
    else
      render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
      flash[:notice] = "Book was successfully destroyed"
      redirect_to books_path
    else
      render :new
    end
  end
  
  

  private

  def book_params
    params.require(:book).permit(:title, :body, :user_id)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top 
  end
  
  def about
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
 
  def search
    @range = params[:range]
    
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
     if @user == current_user
       render :edit
     else
       redirect_to user_path(current_user)
     end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  
  def following
    @user = User.find(params[:id])
    @users = @user.following
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.followers
  end
  
  

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comment_helper.rb
module BookCommentHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <span style="color: white;"><%= link_to "Bookers", root_path, class:"header_title" %></span>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                    <li>
                      <%= link_to "Home", user_path(current_user.id), class: 'fas fa-home nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Users", users_path, class: 'fas fa-users nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
                    </li>
                    <li class="nav-item">
                      <%= link_to "logout", destroy_user_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %>
                    </li>

                  <% else %>
                    <li class="nav-item">
                      <%= link_to "Home", root_path, class: 'fas fa-home nav-link text-light' %>
                    </li>

                    <li class="nav-item">
                      <%= link_to "About", about_path, class: 'fas fa-link nav-link text-light' %>
                    </li>

                    <li class="nav-item">
                      <%= link_to "sign up", new_user_registration_path, class: 'fas fa-user-plus nav-link text-light' %>
                    </li>

                    <li class="nav-item">
                      <%= link_to "login", new_user_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %>
                    </li>
                  <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <% if user_signed_in? %>
            <%= form_with url: search_path, method: :get, local: true do |f| %>
              <%= f.text_field :word %>
              <%= f.select :range, options_for_select([['User'], ['Book']]) %>
              <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["部分一致","partial_match"], ["前方一致","forward_match"], ["後方一致","backward_match"]]) %>
              <%= f.submit "検索" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>

    <p class="notice"><%= notice %></p>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <P>CopyRight Infratop.inc</P>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>